import os

# Telegram
TELEGRAM_TOKEN = "8893369285:AAHvZEWi9F6g5QpiXfpSLFo8YgV0TiTevIU"
TELEGRAM_CHAT_ID = "6953501418"
# Trading Settings
TREND_TIMEFRAME = "4h"
ENTRY_TIMEFRAME = "1h"
MAX_SIGNALS = 4

SYMBOLS = [

    "BTC_USDT",
    "ETH_USDT",
    "SOL_USDT",
    "XRP_USDT",
    "DOGE_USDT",
    "AVAX_USDT",
    "LINK_USDT",
    "ADA_USDT",
    "SUI_USDT",
    "WLD_USDT",
    "NEAR_USDT",
    "INJ_USDT",
    "SEI_USDT",
    "TIA_USDT"

]